#
# Marlin Firmware
# config.ini - Options to apply before the build
#
[config:base]
ini_use_config                           = all
config_export                           = 2

# Load all config: sections in this file
;ini_use_config                          = all
# Load config file relative to Marlin/
;ini_use_config                          = another.ini
# Download configurations from GitHub
;ini_use_config                          = example/Creality/Ender-5 Plus @ bugfix-2.1.x
# Download configurations from your server
;ini_use_config                          = https://me.myserver.com/path/to/configs
# Evaluate config:base and do a config dump
;ini_use_config                          = base
;config_export                           = 2

[config:minimal]
#show_bootscreen                          = 1
#show_custom_bootscreen                   = 1
string_config_h_author                   = "(martin, mpcnc)"

motherboard                              = BOARD_BTT_SKR_V3_0_EZ
serial_port                              = 1
baudrate                                 = 115200
serial_port_2                            = -1
serial_port_3                            = 3

x_driver_type                            = TMC2130
y_driver_type                            = TMC2130
z_driver_type                            = TMC2130
x2_driver_type                           = TMC2130
y2_driver_type                           = TMC2130

extruders                                = 0

temp_sensor_bed                          = 0


#Default Settings
default_axis_steps_per_unit              = { 100, 100, 400 }
default_max_feedrate                     = { 50, 50, 15 }
default_max_acceleration                 = { 180, 180, 80 }

default_acceleration                     = 180
default_travel_acceleration              = 180

junction_deviation_mm                    = 0.04

s_curve_acceleration                     = 1

disable_x                                = 0
disable_y                                = 0
disable_z                                = 0

disable_e                                = 0

x_bed_size                               = 800
x_min_pos                                = 0
x_max_pos                                = X_BED_SIZE

y_bed_size                               = 600
y_min_pos                                = 0
y_max_pos                                = Y_BED_SIZE


min_software_endstop_z                   = 0
max_software_endstops                    = 0

homing_feedrate_mm_m                     =  { (35*60), (35*60), (4*60) }

eeprom_settings                          = 1
eeprom_auto_init                         = 1

has_media                                = 1

individual_acis_homing_menu              = 1

#reprap_discount_full_graphic_smart_controller = 1


neopixel_led                             = 1

[config:advanced]

invert_x2_vs_x_dir                       = 1
x_dual_endstops                          = 1

invert_y2_vs_y_dir                       = 1
y_dual_endstops                          = 1

axis_relative_modes                      = { false, false, false }

adaptive_step_smoothing                  = 1

manual_feedrate                          = { 50*60, 50*60, 4*60 }

auto_report_sd_status                    = 1

sdcard_connection                        = ONBOARD         

babystepping                             = 1

emergency_parser                         = 1

serial_float_precision                   = 4

monitor_driver_status                    = 1

cnc_coordinate_systems                   = 1

auto_report_position                     = 1

m115_geometry_report                     = 1

m114_detail                              = 1

gcode_motion_modes                       = 1

#custom_menu_main                         = 1

#custom_menu_main_title                   = "mpcnc Custom Menu"

#main_menu_item_1_desc                    = "Reset All Coordinates" # "Home & UBL Info"
#main_menu_item_1_gcode                   = "G92 X0 Y0 Z0" # "G28\nG29 W"

#main_menu_item_2_desc                    = "Home Z Axis" # "Preheat for " PREHEAT_1_LABEL
#main_menu_item_2_gcode                   =  "G28 Z" # "M140 S" STRINGIFY(PREHEAT_1_TEMP_BED) "\nM104 S" STRINGIFY(PREHEAT_1_TEMP_HOTEND)
 
#main_menu_item_3_desc                    = "Home X&Y" # "Preheat for " PREHEAT_2_LABEL
#main_menu_item_3_gcode                   = "G28 X Y" # "M140 S" STRINGIFY(PREHEAT_2_TEMP_BED) "\nM104 S" STRINGIFY(PREHEAT_2_TEMP_HOTEND)


host_action_commands                     = 1
host_prompt_support                      = 1

direct_pin_control                       = 1

